# Generated by Django 4.2.5 on 2023-09-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shoppingcart_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
