# Generated by Django 4.2.5 on 2023-10-01 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_productlist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
