# Generated by Django 4.2.5 on 2023-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_shoppingcart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
